
export interface LibraryExercise {
  name: string;
  muscle: string;
  videoUrl?: string;
}

export const EXERCISE_LIBRARY: LibraryExercise[] = [
  // PEITO (30)
  { name: 'Supino Reto (Barra)', muscle: 'Peito', videoUrl: 'https://www.youtube.com/watch?v=scfJ-XN9-nU' },
  { name: 'Supino Inclinado (Barra)', muscle: 'Peito', videoUrl: 'https://www.youtube.com/watch?v=SrqOu55lr6A' },
  { name: 'Supino Declinado (Barra)', muscle: 'Peito' },
  { name: 'Supino Reto (Haltere)', muscle: 'Peito', videoUrl: 'https://www.youtube.com/watch?v=VmBQ6scIbe4' },
  { name: 'Supino Inclinado (Haltere)', muscle: 'Peito', videoUrl: 'https://www.youtube.com/watch?v=5ceR_Kdfid0' },
  { name: 'Supino Declinado (Haltere)', muscle: 'Peito' },
  { name: 'Crucifixo Reto (Haltere)', muscle: 'Peito', videoUrl: 'https://www.youtube.com/watch?v=Yf1v_D_u8bM' },
  { name: 'Crucifixo Inclinado (Haltere)', muscle: 'Peito' },
  { name: 'Crucifixo Declinado (Haltere)', muscle: 'Peito' },
  { name: 'Crossover (Polia Alta)', muscle: 'Peito', videoUrl: 'https://www.youtube.com/watch?v=H74S9DkaBTM' },
  { name: 'Crossover (Polia Média)', muscle: 'Peito' },
  { name: 'Crossover (Polia Baixa)', muscle: 'Peito' },
  { name: 'Fly (Máquina / Pec Deck)', muscle: 'Peito', videoUrl: 'https://www.youtube.com/watch?v=eGjt4lk6g34' },
  { name: 'Supino Máquina Vertical', muscle: 'Peito' },
  { name: 'Supino Máquina Inclinado', muscle: 'Peito' },
  { name: 'Flexão de Braços (Padrão)', muscle: 'Peito', videoUrl: 'https://www.youtube.com/watch?v=mm_SHeu3g9I' },
  { name: 'Flexão de Braços (Inclinada)', muscle: 'Peito' },
  { name: 'Flexão de Braços (Declinada)', muscle: 'Peito' },
  { name: 'Flexão Diamante', muscle: 'Peito' },
  { name: 'Dips / Paralelas (Foco Peito)', muscle: 'Peito' },
  { name: 'Pullovers (Haltere)', muscle: 'Peito' },
  { name: 'Pullovers (Barra)', muscle: 'Peito' },
  { name: 'Supino com Pegada Fechada', muscle: 'Peito' },
  { name: 'Crucifixo na Polia (Banco Reto)', muscle: 'Peito' },
  { name: 'Landmine Press Unilateral', muscle: 'Peito' },
  { name: 'Supino Articulado Convergente', muscle: 'Peito' },
  { name: 'Flexão com Batida de Mão (Pliométrica)', muscle: 'Peito' },
  { name: 'Supino com Elástico', muscle: 'Peito' },
  { name: 'Fly Inclinação Variável', muscle: 'Peito' },
  { name: 'Crushing Press (Halteres juntos)', muscle: 'Peito' },

  // COSTAS (35)
  { name: 'Puxada Aberta (Pulley)', muscle: 'Costas', videoUrl: 'https://www.youtube.com/watch?v=iTf2Y6r20m4' },
  { name: 'Puxada Fechada (Triângulo)', muscle: 'Costas', videoUrl: 'https://www.youtube.com/watch?v=8XQshh4P8n8' },
  { name: 'Puxada Supinada', muscle: 'Costas' },
  { name: 'Puxada Unilateral na Polia', muscle: 'Costas' },
  { name: 'Remada Curvada (Barra)', muscle: 'Costas', videoUrl: 'https://www.youtube.com/watch?v=R322A0uUv7Y' },
  { name: 'Remada Curvada (Supinada)', muscle: 'Costas' },
  { name: 'Remada Unilateral (Serrote)', muscle: 'Costas', videoUrl: 'https://www.youtube.com/watch?v=Yp69I-5o_8U' },
  { name: 'Remada Baixa (Triângulo)', muscle: 'Costas', videoUrl: 'https://www.youtube.com/watch?v=9_H2cWvD-I8' },
  { name: 'Remada Baixa (Barra Reta)', muscle: 'Costas' },
  { name: 'Remada Cavalinho (Barra T)', muscle: 'Costas' },
  { name: 'Levantamento Terra (Convencional)', muscle: 'Costas', videoUrl: 'https://www.youtube.com/watch?v=r4MzxtBKyNE' },
  { name: 'Levantamento Terra (Sumô)', muscle: 'Costas' },
  { name: 'Pull Down (Corda)', muscle: 'Costas', videoUrl: 'https://www.youtube.com/watch?v=I0T6L6eWJ8g' },
  { name: 'Pull Down (Barra Reta)', muscle: 'Costas' },
  { name: 'Barra Fixa (Pronada)', muscle: 'Costas', videoUrl: 'https://www.youtube.com/watch?v=fXvYIq9n1pA' },
  { name: 'Barra Fixa (Supinada / Chin-up)', muscle: 'Costas' },
  { name: 'Barra Fixa (Neutra / Triângulo)', muscle: 'Costas' },
  { name: 'Remada Articulada Aberta', muscle: 'Costas' },
  { name: 'Remada Articulada Fechada', muscle: 'Costas' },
  { name: 'Remada na Máquina (Sentado)', muscle: 'Costas' },
  { name: 'Lombar / Extensão de Tronco', muscle: 'Costas' },
  { name: 'Good Morning (Bom Dia)', muscle: 'Costas' },
  { name: 'Face Pull (Foco Trapézio Médio)', muscle: 'Costas' },
  { name: 'Remada Pendlay', muscle: 'Costas' },
  { name: 'Puxada com Braços Estendidos', muscle: 'Costas' },
  { name: 'Remada no Banco Inclinado', muscle: 'Costas' },
  { name: 'Remada Unilateral Maquina', muscle: 'Costas' },
  { name: 'Puxada na Frente com Pegada Inversa', muscle: 'Costas' },
  { name: 'Levantamento Terra com Halteres', muscle: 'Costas' },
  { name: 'Rack Pulls', muscle: 'Costas' },
  { name: 'Remada Renegade', muscle: 'Costas' },
  { name: 'Remada com Elástico', muscle: 'Costas' },
  { name: 'Puxada Hammer Grip', muscle: 'Costas' },
  { name: 'Remada Unilateral com Apoio no Banco', muscle: 'Costas' },
  { name: 'Meio Levantamento Terra', muscle: 'Costas' },

  // PERNAS / GLÚTEOS (45)
  { name: 'Agachamento Livre (Barra)', muscle: 'Pernas', videoUrl: 'https://www.youtube.com/watch?v=VnPVL7O2I_k' },
  { name: 'Agachamento Frontal (Barra)', muscle: 'Pernas' },
  { name: 'Agachamento Hack', muscle: 'Pernas' },
  { name: 'Agachamento Smith', muscle: 'Pernas' },
  { name: 'Agachamento Goblet (Haltere)', muscle: 'Pernas' },
  { name: 'Agachamento Sumô (Haltere)', muscle: 'Pernas' },
  { name: 'Leg Press 45', muscle: 'Pernas', videoUrl: 'https://www.youtube.com/watch?v=S0Q6e8j-idA' },
  { name: 'Leg Press Horizontal', muscle: 'Pernas' },
  { name: 'Leg Press Unilateral', muscle: 'Pernas' },
  { name: 'Cadeira Extensora', muscle: 'Pernas', videoUrl: 'https://www.youtube.com/watch?v=8lJmBv4-E14' },
  { name: 'Mesa Flexora (Deitada)', muscle: 'Pernas', videoUrl: 'https://www.youtube.com/watch?v=Lq1dE_Q_D-c' },
  { name: 'Cadeira Flexora (Sentada)', muscle: 'Pernas', videoUrl: 'https://www.youtube.com/watch?v=2e6I7nS6r_M' },
  { name: 'Flexora em Pé Unilateral', muscle: 'Pernas' },
  { name: 'Afundo / Avanço (Haltere)', muscle: 'Pernas', videoUrl: 'https://www.youtube.com/watch?v=QOVaHWMqS_I' },
  { name: 'Afundo / Avanço (Barra)', muscle: 'Pernas' },
  { name: 'Agachamento Búlgaro', muscle: 'Pernas' },
  { name: 'Passada (Haltere)', muscle: 'Pernas' },
  { name: 'Stiff (Barra)', muscle: 'Pernas', videoUrl: 'https://www.youtube.com/watch?v=D-Zp4fL8wLo' },
  { name: 'Stiff (Haltere)', muscle: 'Pernas' },
  { name: 'Cadeira Abdutora', muscle: 'Pernas', videoUrl: 'https://www.youtube.com/watch?v=v0l2QW97gL0' },
  { name: 'Cadeira Adutora', muscle: 'Pernas', videoUrl: 'https://www.youtube.com/watch?v=CqS3X0_K_fI' },
  { name: 'Gêmeos em Pé (Máquina)', muscle: 'Pernas', videoUrl: 'https://www.youtube.com/watch?v=mD0D0vSra8E' },
  { name: 'Gêmeos Sentado (Cavalinho)', muscle: 'Pernas' },
  { name: 'Gêmeos no Leg Press', muscle: 'Pernas' },
  { name: 'Gêmeos Unilateral em Pé', muscle: 'Pernas' },
  { name: 'Elevação Pélvica (Barra)', muscle: 'Pernas' },
  { name: 'Elevação Pélvica (Máquina)', muscle: 'Pernas' },
  { name: 'Coice na Polia Baixa', muscle: 'Pernas' },
  { name: 'Glúteo na Máquina', muscle: 'Pernas' },
  { name: 'Abdução de Quadril (Caneleira)', muscle: 'Pernas' },
  { name: 'Extensão de Quadril (Banco)', muscle: 'Pernas' },
  { name: 'Step up (Subida no Banco)', muscle: 'Pernas' },
  { name: 'Sissy Squat', muscle: 'Pernas' },
  { name: 'Agachamento com Elástico', muscle: 'Pernas' },
  { name: 'Agachamento com Salto (Pliometria)', muscle: 'Pernas' },
  { name: 'Leg Press Fechado', muscle: 'Pernas' },
  { name: 'Leg Press Aberto (Sumô)', muscle: 'Pernas' },
  { name: 'Good Morning Pernas Estendidas', muscle: 'Pernas' },
  { name: 'Abdução com Mini Band', muscle: 'Pernas' },
  { name: 'Gêmeos Smith', muscle: 'Pernas' },
  { name: 'Agachamento Cossaco', muscle: 'Pernas' },
  { name: 'Nordic Curls', muscle: 'Pernas' },
  { name: 'Pistol Squat (Unilateral)', muscle: 'Pernas' },
  { name: 'Flexão de Isquiotibiais com Bola', muscle: 'Pernas' },
  { name: 'Remada Lateral (Slide)', muscle: 'Pernas' },

  // OMBROS (25)
  { name: 'Desenvolvimento (Barra)', muscle: 'Ombros', videoUrl: 'https://www.youtube.com/watch?v=7XF9pEnpYnI' },
  { name: 'Desenvolvimento (Haltere)', muscle: 'Ombros', videoUrl: 'https://www.youtube.com/watch?v=V_F9p8G7N_8' },
  { name: 'Desenvolvimento Arnold', muscle: 'Ombros' },
  { name: 'Desenvolvimento Militar (Militar Press)', muscle: 'Ombros' },
  { name: 'Desenvolvimento na Máquina', muscle: 'Ombros' },
  { name: 'Elevação Lateral (Haltere)', muscle: 'Ombros', videoUrl: 'https://www.youtube.com/watch?v=P_XfVf8_1Yk' },
  { name: 'Elevação Lateral (Polia)', muscle: 'Ombros' },
  { name: 'Elevação Lateral (Máquina)', muscle: 'Ombros' },
  { name: 'Elevação Frontal (Barra)', muscle: 'Ombros', videoUrl: 'https://www.youtube.com/watch?v=9S_X3k9vE88' },
  { name: 'Elevação Frontal (Haltere)', muscle: 'Ombros' },
  { name: 'Elevação Frontal (Anilha)', muscle: 'Ombros' },
  { name: 'Posterior de Ombro (Crucifixo Inverso Haltere)', muscle: 'Ombros' },
  { name: 'Posterior de Ombro (Crucifixo Inverso Polia)', muscle: 'Ombros' },
  { name: 'Posterior de Ombro (Corda / Face Pull)', muscle: 'Ombros', videoUrl: 'https://www.youtube.com/watch?v=VAsyX6eXj4I' },
  { name: 'Posterior de Ombro (Peck Deck Inverso)', muscle: 'Ombros' },
  { name: 'Encolhimento (Haltere)', muscle: 'Ombros' },
  { name: 'Encolhimento (Barra)', muscle: 'Ombros' },
  { name: 'Encolhimento (Polia)', muscle: 'Ombros' },
  { name: 'Remada Alta (Barra)', muscle: 'Ombros' },
  { name: 'Remada Alta (Polia)', muscle: 'Ombros' },
  { name: 'Desenvolvimento com Pegada Neutra', muscle: 'Ombros' },
  { name: 'Elevação Lateral Inclinada', muscle: 'Ombros' },
  { name: 'Rotação Externa na Polia', muscle: 'Ombros' },
  { name: 'Rotação Interna na Polia', muscle: 'Ombros' },
  { name: 'Y-Raise Unilateral Polia', muscle: 'Ombros' },

  // BÍCEPS / ANTEBRAÇO (30)
  { name: 'Rosca Direta (Barra E-Z)', muscle: 'Bíceps', videoUrl: 'https://www.youtube.com/watch?v=zC3nLl_R_aE' },
  { name: 'Rosca Direta (Barra Reta)', muscle: 'Bíceps' },
  { name: 'Rosca Direta (Polia)', muscle: 'Bíceps' },
  { name: 'Rosca Alternada (Haltere)', muscle: 'Bíceps', videoUrl: 'https://www.youtube.com/watch?v=WCSx9jA_P-s' },
  { name: 'Rosca Martelo (Haltere)', muscle: 'Bíceps', videoUrl: 'https://www.youtube.com/watch?v=zK9qI-X08o8' },
  { name: 'Rosca Martelo (Corda Polia)', muscle: 'Bíceps' },
  { name: 'Rosca Concentrada', muscle: 'Bíceps', videoUrl: 'https://www.youtube.com/watch?v=R0_InG812yU' },
  { name: 'Rosca Scott (Barra E-Z)', muscle: 'Bíceps', videoUrl: 'https://www.youtube.com/watch?v=680pZ7-YofA' },
  { name: 'Rosca Scott (Máquina)', muscle: 'Bíceps' },
  { name: 'Rosca Scott (Haltere Unilateral)', muscle: 'Bíceps' },
  { name: 'Rosca 21 (Barra)', muscle: 'Bíceps' },
  { name: 'Rosca Inclinada (Banco 45 Haltere)', muscle: 'Bíceps' },
  { name: 'Rosca Spider (Banco Inclinado)', muscle: 'Bíceps' },
  { name: 'Rosca Zottman', muscle: 'Bíceps' },
  { name: 'Bíceps Duplo no Pulley', muscle: 'Bíceps' },
  { name: 'Rosca Unilateral na Polia', muscle: 'Bíceps' },
  { name: 'Rosca na Barra W (Pegada Inversa)', muscle: 'Antebraço' },
  { name: 'Flexão de Punho (Barra)', muscle: 'Antebraço' },
  { name: 'Extensão de Punho (Barra)', muscle: 'Antebraço' },
  { name: 'Flexão de Punho (Haltere Unilateral)', muscle: 'Antebraço' },
  { name: 'Extensão de Punho (Haltere Unilateral)', muscle: 'Antebraço' },
  { name: 'Rosca Inversa (Polia)', muscle: 'Antebraço' },
  { name: 'Caminhada do Fazendeiro (Farmer Walk)', muscle: 'Antebraço' },
  { name: 'Rosca com Pegada Neutra (Martelo Inclinado)', muscle: 'Bíceps' },
  { name: 'Rosca Aranha (Halteres)', muscle: 'Bíceps' },
  { name: 'Rosca na Máquina Hammer', muscle: 'Bíceps' },
  { name: 'Pendurar na Barra (Grip Strength)', muscle: 'Antebraço' },
  { name: 'Rosca Martelo Cruzada', muscle: 'Bíceps' },
  { name: 'Flexão de Punho Polia', muscle: 'Antebraço' },
  { name: 'Extensão de Punho Polia', muscle: 'Antebraço' },

  // TRÍCEPS (25)
  { name: 'Tríceps Pulley (Barra Reta)', muscle: 'Tríceps', videoUrl: 'https://www.youtube.com/watch?v=8y1Z_p-D_y4' },
  { name: 'Tríceps Pulley (Barra W)', muscle: 'Tríceps' },
  { name: 'Tríceps Pulley (Barra V)', muscle: 'Tríceps' },
  { name: 'Tríceps Corda', muscle: 'Tríceps', videoUrl: 'https://www.youtube.com/watch?v=N_pE0uUp_8Y' },
  { name: 'Tríceps Testa (Barra E-Z)', muscle: 'Tríceps', videoUrl: 'https://www.youtube.com/watch?v=3n4N8B3_N_U' },
  { name: 'Tríceps Testa (Halteres)', muscle: 'Tríceps' },
  { name: 'Tríceps Francês (Haltere Unilateral)', muscle: 'Tríceps', videoUrl: 'https://www.youtube.com/watch?v=R1z6A50jXJk' },
  { name: 'Tríceps Francês (Barra Sentado)', muscle: 'Tríceps' },
  { name: 'Tríceps Francês (Polia Baixa)', muscle: 'Tríceps' },
  { name: 'Mergulho em Paralelas', muscle: 'Tríceps', videoUrl: 'https://www.youtube.com/watch?v=2z8JmcrW-As' },
  { name: 'Mergulho no Banco (Dips)', muscle: 'Tríceps' },
  { name: 'Tríceps Coice (Haltere)', muscle: 'Tríceps' },
  { name: 'Tríceps Coice (Polia)', muscle: 'Tríceps' },
  { name: 'Extensão de Tríceps Deitado (Haltere)', muscle: 'Tríceps' },
  { name: 'Supino com Pegada Estreita', muscle: 'Tríceps' },
  { name: 'Tríceps Polia Inversa (Mão Supinada)', muscle: 'Tríceps' },
  { name: 'Tríceps Máquina', muscle: 'Tríceps' },
  { name: 'Tríceps Unilateral Corda', muscle: 'Tríceps' },
  { name: 'Tríceps Testa na Polia', muscle: 'Tríceps' },
  { name: 'Tríceps Katana (Polia Alta)', muscle: 'Tríceps' },
  { name: 'Flexão com Cotovelos Fechados', muscle: 'Tríceps' },
  { name: 'JM Press', muscle: 'Tríceps' },
  { name: 'Tríceps Skull Crusher Declinado', muscle: 'Tríceps' },
  { name: 'Tríceps Corda Acima da Cabeça', muscle: 'Tríceps' },
  { name: 'Tríceps Francês Unilateral Polia', muscle: 'Tríceps' },

  // ABDÔMEN / CORE (25)
  { name: 'Abdominal Supra (Solo)', muscle: 'Abdômen', videoUrl: 'https://www.youtube.com/watch?v=5_Xm7rI-7Wk' },
  { name: 'Abdominal Infra (Elevação de Pernas)', muscle: 'Abdômen', videoUrl: 'https://www.youtube.com/watch?v=z2vR7p0_Z4E' },
  { name: 'Plancha Isométrica (Frontal)', muscle: 'Abdômen', videoUrl: 'https://www.youtube.com/watch?v=pSHjTRCQxIw' },
  { name: 'Plancha Lateral', muscle: 'Abdômen' },
  { name: 'Abdominal Bicicleta', muscle: 'Abdômen' },
  { name: 'Abdominal no Pulley (Corda / Crunch Polia)', muscle: 'Abdômen' },
  { name: 'Elevação de Pernas Pendurado (Barra)', muscle: 'Abdômen' },
  { name: 'Prancha com Toque nos Ombros', muscle: 'Abdômen' },
  { name: 'Prancha Spider-Man', muscle: 'Abdômen' },
  { name: 'Abdominal Supra Máquina', muscle: 'Abdômen' },
  { name: 'Abdominal Canivete', muscle: 'Abdômen' },
  { name: 'Roda Abdominal (Ab Wheel)', muscle: 'Abdômen' },
  { name: 'Woodchopper (Lenhador Polia)', muscle: 'Abdômen' },
  { name: 'Russian Twist (Giro Russo)', muscle: 'Abdômen' },
  { name: 'Dead Bug', muscle: 'Abdômen' },
  { name: 'Bird Dog', muscle: 'Abdômen' },
  { name: 'Hollow Body Hold', muscle: 'Abdômen' },
  { name: 'Mountain Climbers', muscle: 'Abdômen' },
  { name: 'Abdominal Infra no Banco Inclinado', muscle: 'Abdômen' },
  { name: 'Abdominal Remador', muscle: 'Abdômen' },
  { name: 'Giro de Tronco com Bastão', muscle: 'Abdômen' },
  { name: 'Abdominal Infra Unilateral', muscle: 'Abdômen' },
  { name: 'Prancha com Elevação de Perna', muscle: 'Abdômen' },
  { name: 'L-Sit (Tentativa/Hold)', muscle: 'Abdômen' },
  { name: 'Abdominal Oblíquo deitado', muscle: 'Abdômen' },

];

export const MUSCLE_GROUPS = Array.from(new Set(EXERCISE_LIBRARY.map(ex => ex.muscle)));
